<?php
/**
 * GetAcquiringSlugCurrencies200ResponseCurrenciesInner
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PayPlayClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PayPlay API
 *
 * PayPlay API documentation generated from markdown files
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PayPlayClient\Model;

use \ArrayAccess;
use \PayPlayClient\ObjectSerializer;

/**
 * GetAcquiringSlugCurrencies200ResponseCurrenciesInner Class Doc Comment
 *
 * @category Class
 * @package  PayPlayClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetAcquiringSlugCurrencies200ResponseCurrenciesInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'getAcquiringSlugCurrencies_200_response_currencies_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'precision' => 'float',
        'icon' => 'string',
        'ticker' => 'string',
        'is_fiat' => 'bool',
        'is_stable' => 'bool',
        'name' => 'string',
        'limits' => '\PayPlayClient\Model\GetAcquiringSlugCurrencies200ResponseCurrenciesInnerLimits',
        'min' => 'string',
        'max' => 'string',
        'preset_donation_values' => 'string[]',
        'networks' => '\PayPlayClient\Model\GetAcquiringSlugCurrencies200ResponseCurrenciesInnerNetworks',
        'exchange_rate' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'precision' => null,
        'icon' => null,
        'ticker' => null,
        'is_fiat' => null,
        'is_stable' => null,
        'name' => null,
        'limits' => null,
        'min' => null,
        'max' => null,
        'preset_donation_values' => null,
        'networks' => null,
        'exchange_rate' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'precision' => false,
        'icon' => false,
        'ticker' => false,
        'is_fiat' => false,
        'is_stable' => false,
        'name' => false,
        'limits' => false,
        'min' => false,
        'max' => false,
        'preset_donation_values' => false,
        'networks' => false,
        'exchange_rate' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'precision' => 'precision',
        'icon' => 'icon',
        'ticker' => 'ticker',
        'is_fiat' => 'is_fiat',
        'is_stable' => 'is_stable',
        'name' => 'name',
        'limits' => 'limits',
        'min' => 'min',
        'max' => 'max',
        'preset_donation_values' => 'preset_donation_values',
        'networks' => 'networks',
        'exchange_rate' => 'exchange_rate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'precision' => 'setPrecision',
        'icon' => 'setIcon',
        'ticker' => 'setTicker',
        'is_fiat' => 'setIsFiat',
        'is_stable' => 'setIsStable',
        'name' => 'setName',
        'limits' => 'setLimits',
        'min' => 'setMin',
        'max' => 'setMax',
        'preset_donation_values' => 'setPresetDonationValues',
        'networks' => 'setNetworks',
        'exchange_rate' => 'setExchangeRate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'precision' => 'getPrecision',
        'icon' => 'getIcon',
        'ticker' => 'getTicker',
        'is_fiat' => 'getIsFiat',
        'is_stable' => 'getIsStable',
        'name' => 'getName',
        'limits' => 'getLimits',
        'min' => 'getMin',
        'max' => 'getMax',
        'preset_donation_values' => 'getPresetDonationValues',
        'networks' => 'getNetworks',
        'exchange_rate' => 'getExchangeRate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('precision', $data ?? [], null);
        $this->setIfExists('icon', $data ?? [], null);
        $this->setIfExists('ticker', $data ?? [], null);
        $this->setIfExists('is_fiat', $data ?? [], null);
        $this->setIfExists('is_stable', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('limits', $data ?? [], null);
        $this->setIfExists('min', $data ?? [], null);
        $this->setIfExists('max', $data ?? [], null);
        $this->setIfExists('preset_donation_values', $data ?? [], null);
        $this->setIfExists('networks', $data ?? [], null);
        $this->setIfExists('exchange_rate', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['precision'] === null) {
            $invalidProperties[] = "'precision' can't be null";
        }
        if ($this->container['icon'] === null) {
            $invalidProperties[] = "'icon' can't be null";
        }
        if ($this->container['ticker'] === null) {
            $invalidProperties[] = "'ticker' can't be null";
        }
        if ($this->container['is_fiat'] === null) {
            $invalidProperties[] = "'is_fiat' can't be null";
        }
        if ($this->container['is_stable'] === null) {
            $invalidProperties[] = "'is_stable' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['limits'] === null) {
            $invalidProperties[] = "'limits' can't be null";
        }
        if ($this->container['min'] === null) {
            $invalidProperties[] = "'min' can't be null";
        }
        if ($this->container['max'] === null) {
            $invalidProperties[] = "'max' can't be null";
        }
        if ($this->container['preset_donation_values'] === null) {
            $invalidProperties[] = "'preset_donation_values' can't be null";
        }
        if ($this->container['networks'] === null) {
            $invalidProperties[] = "'networks' can't be null";
        }
        if ($this->container['exchange_rate'] === null) {
            $invalidProperties[] = "'exchange_rate' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets precision
     *
     * @return float
     */
    public function getPrecision()
    {
        return $this->container['precision'];
    }

    /**
     * Sets precision
     *
     * @param float $precision precision
     *
     * @return self
     */
    public function setPrecision($precision)
    {
        if (is_null($precision)) {
            throw new \InvalidArgumentException('non-nullable precision cannot be null');
        }
        $this->container['precision'] = $precision;

        return $this;
    }

    /**
     * Gets icon
     *
     * @return string
     */
    public function getIcon()
    {
        return $this->container['icon'];
    }

    /**
     * Sets icon
     *
     * @param string $icon icon
     *
     * @return self
     */
    public function setIcon($icon)
    {
        if (is_null($icon)) {
            throw new \InvalidArgumentException('non-nullable icon cannot be null');
        }
        $this->container['icon'] = $icon;

        return $this;
    }

    /**
     * Gets ticker
     *
     * @return string
     */
    public function getTicker()
    {
        return $this->container['ticker'];
    }

    /**
     * Sets ticker
     *
     * @param string $ticker ticker
     *
     * @return self
     */
    public function setTicker($ticker)
    {
        if (is_null($ticker)) {
            throw new \InvalidArgumentException('non-nullable ticker cannot be null');
        }
        $this->container['ticker'] = $ticker;

        return $this;
    }

    /**
     * Gets is_fiat
     *
     * @return bool
     */
    public function getIsFiat()
    {
        return $this->container['is_fiat'];
    }

    /**
     * Sets is_fiat
     *
     * @param bool $is_fiat is_fiat
     *
     * @return self
     */
    public function setIsFiat($is_fiat)
    {
        if (is_null($is_fiat)) {
            throw new \InvalidArgumentException('non-nullable is_fiat cannot be null');
        }
        $this->container['is_fiat'] = $is_fiat;

        return $this;
    }

    /**
     * Gets is_stable
     *
     * @return bool
     */
    public function getIsStable()
    {
        return $this->container['is_stable'];
    }

    /**
     * Sets is_stable
     *
     * @param bool $is_stable is_stable
     *
     * @return self
     */
    public function setIsStable($is_stable)
    {
        if (is_null($is_stable)) {
            throw new \InvalidArgumentException('non-nullable is_stable cannot be null');
        }
        $this->container['is_stable'] = $is_stable;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets limits
     *
     * @return \PayPlayClient\Model\GetAcquiringSlugCurrencies200ResponseCurrenciesInnerLimits
     */
    public function getLimits()
    {
        return $this->container['limits'];
    }

    /**
     * Sets limits
     *
     * @param \PayPlayClient\Model\GetAcquiringSlugCurrencies200ResponseCurrenciesInnerLimits $limits limits
     *
     * @return self
     */
    public function setLimits($limits)
    {
        if (is_null($limits)) {
            throw new \InvalidArgumentException('non-nullable limits cannot be null');
        }
        $this->container['limits'] = $limits;

        return $this;
    }

    /**
     * Gets min
     *
     * @return string
     */
    public function getMin()
    {
        return $this->container['min'];
    }

    /**
     * Sets min
     *
     * @param string $min min
     *
     * @return self
     */
    public function setMin($min)
    {
        if (is_null($min)) {
            throw new \InvalidArgumentException('non-nullable min cannot be null');
        }
        $this->container['min'] = $min;

        return $this;
    }

    /**
     * Gets max
     *
     * @return string
     */
    public function getMax()
    {
        return $this->container['max'];
    }

    /**
     * Sets max
     *
     * @param string $max max
     *
     * @return self
     */
    public function setMax($max)
    {
        if (is_null($max)) {
            throw new \InvalidArgumentException('non-nullable max cannot be null');
        }
        $this->container['max'] = $max;

        return $this;
    }

    /**
     * Gets preset_donation_values
     *
     * @return string[]
     */
    public function getPresetDonationValues()
    {
        return $this->container['preset_donation_values'];
    }

    /**
     * Sets preset_donation_values
     *
     * @param string[] $preset_donation_values preset_donation_values
     *
     * @return self
     */
    public function setPresetDonationValues($preset_donation_values)
    {
        if (is_null($preset_donation_values)) {
            throw new \InvalidArgumentException('non-nullable preset_donation_values cannot be null');
        }
        $this->container['preset_donation_values'] = $preset_donation_values;

        return $this;
    }

    /**
     * Gets networks
     *
     * @return \PayPlayClient\Model\GetAcquiringSlugCurrencies200ResponseCurrenciesInnerNetworks
     */
    public function getNetworks()
    {
        return $this->container['networks'];
    }

    /**
     * Sets networks
     *
     * @param \PayPlayClient\Model\GetAcquiringSlugCurrencies200ResponseCurrenciesInnerNetworks $networks networks
     *
     * @return self
     */
    public function setNetworks($networks)
    {
        if (is_null($networks)) {
            throw new \InvalidArgumentException('non-nullable networks cannot be null');
        }
        $this->container['networks'] = $networks;

        return $this;
    }

    /**
     * Gets exchange_rate
     *
     * @return string
     */
    public function getExchangeRate()
    {
        return $this->container['exchange_rate'];
    }

    /**
     * Sets exchange_rate
     *
     * @param string $exchange_rate exchange_rate
     *
     * @return self
     */
    public function setExchangeRate($exchange_rate)
    {
        if (is_null($exchange_rate)) {
            throw new \InvalidArgumentException('non-nullable exchange_rate cannot be null');
        }
        $this->container['exchange_rate'] = $exchange_rate;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


