<?php
/**
 * GetCurrenciesCurrencies1200ResponseCurrenciesInnerLimits
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PayPlayClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PayPlay API
 *
 * PayPlay API documentation generated from markdown files
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PayPlayClient\Model;

use \ArrayAccess;
use \PayPlayClient\ObjectSerializer;

/**
 * GetCurrenciesCurrencies1200ResponseCurrenciesInnerLimits Class Doc Comment
 *
 * @category Class
 * @package  PayPlayClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetCurrenciesCurrencies1200ResponseCurrenciesInnerLimits implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'getCurrenciesCurrencies1_200_response_currencies_inner_limits';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'erc20' => '\PayPlayClient\Model\GetCurrenciesCurrencies1200ResponseCurrenciesInnerLimitsERC20',
        'ton' => '\PayPlayClient\Model\GetCurrenciesCurrencies1200ResponseCurrenciesInnerLimitsERC20',
        'trc20' => '\PayPlayClient\Model\GetCurrenciesCurrencies1200ResponseCurrenciesInnerLimitsERC20'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'erc20' => null,
        'ton' => null,
        'trc20' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'erc20' => false,
        'ton' => false,
        'trc20' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'erc20' => 'ERC20',
        'ton' => 'TON',
        'trc20' => 'TRC20'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'erc20' => 'setErc20',
        'ton' => 'setTon',
        'trc20' => 'setTrc20'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'erc20' => 'getErc20',
        'ton' => 'getTon',
        'trc20' => 'getTrc20'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('erc20', $data ?? [], null);
        $this->setIfExists('ton', $data ?? [], null);
        $this->setIfExists('trc20', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['erc20'] === null) {
            $invalidProperties[] = "'erc20' can't be null";
        }
        if ($this->container['ton'] === null) {
            $invalidProperties[] = "'ton' can't be null";
        }
        if ($this->container['trc20'] === null) {
            $invalidProperties[] = "'trc20' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets erc20
     *
     * @return \PayPlayClient\Model\GetCurrenciesCurrencies1200ResponseCurrenciesInnerLimitsERC20
     */
    public function getErc20()
    {
        return $this->container['erc20'];
    }

    /**
     * Sets erc20
     *
     * @param \PayPlayClient\Model\GetCurrenciesCurrencies1200ResponseCurrenciesInnerLimitsERC20 $erc20 erc20
     *
     * @return self
     */
    public function setErc20($erc20)
    {
        if (is_null($erc20)) {
            throw new \InvalidArgumentException('non-nullable erc20 cannot be null');
        }
        $this->container['erc20'] = $erc20;

        return $this;
    }

    /**
     * Gets ton
     *
     * @return \PayPlayClient\Model\GetCurrenciesCurrencies1200ResponseCurrenciesInnerLimitsERC20
     */
    public function getTon()
    {
        return $this->container['ton'];
    }

    /**
     * Sets ton
     *
     * @param \PayPlayClient\Model\GetCurrenciesCurrencies1200ResponseCurrenciesInnerLimitsERC20 $ton ton
     *
     * @return self
     */
    public function setTon($ton)
    {
        if (is_null($ton)) {
            throw new \InvalidArgumentException('non-nullable ton cannot be null');
        }
        $this->container['ton'] = $ton;

        return $this;
    }

    /**
     * Gets trc20
     *
     * @return \PayPlayClient\Model\GetCurrenciesCurrencies1200ResponseCurrenciesInnerLimitsERC20
     */
    public function getTrc20()
    {
        return $this->container['trc20'];
    }

    /**
     * Sets trc20
     *
     * @param \PayPlayClient\Model\GetCurrenciesCurrencies1200ResponseCurrenciesInnerLimitsERC20 $trc20 trc20
     *
     * @return self
     */
    public function setTrc20($trc20)
    {
        if (is_null($trc20)) {
            throw new \InvalidArgumentException('non-nullable trc20 cannot be null');
        }
        $this->container['trc20'] = $trc20;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


