<?php
/**
 * DefaultApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  PayPlayClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PayPlay API
 *
 * PayPlay API documentation generated from markdown files
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace PayPlayClient\Test\Api;

use \PayPlayClient\Configuration;
use \PayPlayClient\ApiException;
use \PayPlayClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  PayPlayClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createAcquiring
     *
     * POST /acquiring/{slug}/pay.
     *
     */
    public function testCreateAcquiring()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createBalances
     *
     * POST /private-api/balances/{balanceID}.
     *
     */
    public function testCreateBalances()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createConvertWithdrawal
     *
     * POST /private-api/convert-withdrawal.
     *
     */
    public function testCreateConvertWithdrawal()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createConvertWithdrawal_0
     *
     * POST /private-api/convert-withdrawal/{transactionID}/refresh.
     *
     */
    public function testCreateConvertWithdrawal0()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createConvertWithdrawal_1
     *
     * POST /private-api/convert-withdrawal/{transactionID}/confirm.
     *
     */
    public function testCreateConvertWithdrawal1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createConvertWithdrawal_2
     *
     * POST /private-api/convert-withdrawal/instant.
     *
     */
    public function testCreateConvertWithdrawal2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createCryptoOrders
     *
     * POST /private-api/crypto-orders/{slug}.
     *
     */
    public function testCreateCryptoOrders()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createCryptoOrders_0
     *
     * POST /private-api/crypto-orders/{slug}/{orderID}/complete.
     *
     */
    public function testCreateCryptoOrders0()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createCryptoTopups
     *
     * POST /private-api/crypto-topups/{slug}.
     *
     */
    public function testCreateCryptoTopups()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createMassPayouts
     *
     * POST /mass-payouts.
     *
     */
    public function testCreateMassPayouts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createRefunds
     *
     * POST /private-api/refunds/orders/{orderID}.
     *
     */
    public function testCreateRefunds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createSlug
     *
     * POST /private-api/{slug}/withdrawal.
     *
     */
    public function testCreateSlug()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAcquiringSlugCurrencies
     *
     * GET /acquiring/{slug}/currencies.
     *
     */
    public function testGetAcquiringSlugCurrencies()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAcquiringSlugOrderOrderID
     *
     * GET /acquiring/{slug}/order/{orderID}.
     *
     */
    public function testGetAcquiringSlugOrderOrderID()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBalancesBalanceID
     *
     * GET /private-api/balances/{balanceID}.
     *
     */
    public function testGetBalancesBalanceID()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBalancess
     *
     * GET /private-api/balances/.
     *
     */
    public function testGetBalancess()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getConvertWithdrawalCurrencies
     *
     * GET /private-api/convert-withdrawal/currencies.
     *
     */
    public function testGetConvertWithdrawalCurrencies()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCryptoOrdersSlug
     *
     * GET /private-api/crypto-orders/{slug}.
     *
     */
    public function testGetCryptoOrdersSlug()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCryptoOrdersSlugOrderID
     *
     * GET /private-api/crypto-orders/{slug}/{orderID}.
     *
     */
    public function testGetCryptoOrdersSlugOrderID()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCurrenciesCryptoOrderTargetCurrencies
     *
     * GET /currencies/crypto-order-target-currencies.
     *
     */
    public function testGetCurrenciesCryptoOrderTargetCurrencies()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCurrenciesCryptoTopupTargetCurrencies
     *
     * GET /private-api/currencies/crypto-topup-target-currencies.
     *
     */
    public function testGetCurrenciesCryptoTopupTargetCurrencies()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getExchangeRatesCurrencyTicker
     *
     * GET /private-api/exchange-rates/{currencyTicker}.
     *
     */
    public function testGetExchangeRatesCurrencyTicker()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrderStatusess
     *
     * GET /private-api/order-statuses.
     *
     */
    public function testGetOrderStatusess()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrdersSlug
     *
     * GET /private-api/orders/{slug}.
     *
     */
    public function testGetOrdersSlug()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrdersSlugOrderId
     *
     * GET /private-api/orders/{slug}/{orderId}.
     *
     */
    public function testGetOrdersSlugOrderId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRatess
     *
     * GET /rates.
     *
     */
    public function testGetRatess()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTransactionsTransactionID
     *
     * GET /private-api/transactions/{transactionID}.
     *
     */
    public function testGetTransactionsTransactionID()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTransactionss
     *
     * GET /private-api/transactions.
     *
     */
    public function testGetTransactionss()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWithdrawalsFees
     *
     * GET /private-api/withdrawals/fees.
     *
     */
    public function testGetWithdrawalsFees()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
