<?php
/**
 * GetCurrenciesCurrencies1200ResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PayPlayClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PayPlay API
 *
 * PayPlay API documentation generated from markdown files
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace PayPlayClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetCurrenciesCurrencies1200ResponseTest Class Doc Comment
 *
 * @category    Class
 * @description GetCurrenciesCurrencies1200Response
 * @package     PayPlayClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetCurrenciesCurrencies1200ResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetCurrenciesCurrencies1200Response"
     */
    public function testGetCurrenciesCurrencies1200Response()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "currencies"
     */
    public function testPropertyCurrencies()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
